### ISSUE TITLE
Реализовать хранение документов на сервере

### ISSUE THREAD

**Issue by gemenee** [gemenee/ContactExtractor#1]
## DoD
- [x] Есть возможность положить на сервер документ и данные полученные в результате обработки
- [x] Загруженные документы отображаются в таблице на главной странице.

### Description
 На сервере организовано хранилище, которое позволяет хранить загруженные документы и результаты их обработки

### Tasks
- [x] Модели: 
    - документа
    - результата обработки
- [x] Класс наследник DbContext с реализованным modelBuilder
