### ISSUE TITLE
Извлечение и сохранение текста из документа

### ISSUE THREAD

**Issue by gemenee** [gemenee/ContactExtractor#3]
## DoD
- [x] При загрузке документа автоматически происходит извлечение из него текста

### Description
 Для дальнейшей обработки необходимо извлечь текст из документа и сохранить его для передачи в обработку.

### Tasks
- [x] Метод извлечения текста из документа
- [x] Метод для сохранения текстового файла
