### ISSUE TITLE
API-метод отправки текста на сервер для обработки

### ISSUE THREAD

**Issue by gemenee** [gemenee/ContactExtractor#4]
## DoD
- [x] приложение получает ответ от сервера обработки текста

### Description
 Здесь пока есть варианты: 
 + отправлять поток
 + отправлять текст
 + отправлять ссылку на скачивание текстового файла

### Tasks
- [x] Метод направления запроса
- [x] Класс для полученного ответа (может быть взять уже из готовых, но вряд ли)
- [x] сохранение полученного ответа в БД
